/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DeclarationArticlesEvaluationService } from "../declarationArticlesEvaluation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeclarationArticlesEvaluationCreateInput } from "./DeclarationArticlesEvaluationCreateInput";
import { DeclarationArticlesEvaluation } from "./DeclarationArticlesEvaluation";
import { DeclarationArticlesEvaluationFindManyArgs } from "./DeclarationArticlesEvaluationFindManyArgs";
import { DeclarationArticlesEvaluationWhereUniqueInput } from "./DeclarationArticlesEvaluationWhereUniqueInput";
import { DeclarationArticlesEvaluationUpdateInput } from "./DeclarationArticlesEvaluationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DeclarationArticlesEvaluationControllerBase {
  constructor(
    protected readonly service: DeclarationArticlesEvaluationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DeclarationArticlesEvaluation })
  @nestAccessControl.UseRoles({
    resource: "DeclarationArticlesEvaluation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: DeclarationArticlesEvaluationCreateInput,
  })
  async createDeclarationArticlesEvaluation(
    @common.Body() data: DeclarationArticlesEvaluationCreateInput
  ): Promise<DeclarationArticlesEvaluation> {
    return await this.service.createDeclarationArticlesEvaluation({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DeclarationArticlesEvaluation] })
  @ApiNestedQuery(DeclarationArticlesEvaluationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DeclarationArticlesEvaluation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async declarationArticlesEvaluations(
    @common.Req() request: Request
  ): Promise<DeclarationArticlesEvaluation[]> {
    const args = plainToClass(
      DeclarationArticlesEvaluationFindManyArgs,
      request.query
    );
    return this.service.declarationArticlesEvaluations({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DeclarationArticlesEvaluation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DeclarationArticlesEvaluation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async declarationArticlesEvaluation(
    @common.Param() params: DeclarationArticlesEvaluationWhereUniqueInput
  ): Promise<DeclarationArticlesEvaluation | null> {
    const result = await this.service.declarationArticlesEvaluation({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DeclarationArticlesEvaluation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DeclarationArticlesEvaluation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: DeclarationArticlesEvaluationUpdateInput,
  })
  async updateDeclarationArticlesEvaluation(
    @common.Param() params: DeclarationArticlesEvaluationWhereUniqueInput,
    @common.Body() data: DeclarationArticlesEvaluationUpdateInput
  ): Promise<DeclarationArticlesEvaluation | null> {
    try {
      return await this.service.updateDeclarationArticlesEvaluation({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DeclarationArticlesEvaluation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DeclarationArticlesEvaluation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDeclarationArticlesEvaluation(
    @common.Param() params: DeclarationArticlesEvaluationWhereUniqueInput
  ): Promise<DeclarationArticlesEvaluation | null> {
    try {
      return await this.service.deleteDeclarationArticlesEvaluation({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
