/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeclarationArticlesEvaluation } from "./DeclarationArticlesEvaluation";
import { DeclarationArticlesEvaluationCountArgs } from "./DeclarationArticlesEvaluationCountArgs";
import { DeclarationArticlesEvaluationFindManyArgs } from "./DeclarationArticlesEvaluationFindManyArgs";
import { DeclarationArticlesEvaluationFindUniqueArgs } from "./DeclarationArticlesEvaluationFindUniqueArgs";
import { DeleteDeclarationArticlesEvaluationArgs } from "./DeleteDeclarationArticlesEvaluationArgs";
import { DeclarationArticlesEvaluationService } from "../declarationArticlesEvaluation.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => DeclarationArticlesEvaluation)
export class DeclarationArticlesEvaluationResolverBase {
  constructor(
    protected readonly service: DeclarationArticlesEvaluationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DeclarationArticlesEvaluation",
    action: "read",
    possession: "any",
  })
  async _declarationArticlesEvaluationsMeta(
    @graphql.Args() args: DeclarationArticlesEvaluationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [DeclarationArticlesEvaluation])
  @nestAccessControl.UseRoles({
    resource: "DeclarationArticlesEvaluation",
    action: "read",
    possession: "any",
  })
  async declarationArticlesEvaluations(
    @graphql.Args() args: DeclarationArticlesEvaluationFindManyArgs
  ): Promise<DeclarationArticlesEvaluation[]> {
    return this.service.declarationArticlesEvaluations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => DeclarationArticlesEvaluation, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DeclarationArticlesEvaluation",
    action: "read",
    possession: "own",
  })
  async declarationArticlesEvaluation(
    @graphql.Args() args: DeclarationArticlesEvaluationFindUniqueArgs
  ): Promise<DeclarationArticlesEvaluation | null> {
    const result = await this.service.declarationArticlesEvaluation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DeclarationArticlesEvaluation)
  @nestAccessControl.UseRoles({
    resource: "DeclarationArticlesEvaluation",
    action: "delete",
    possession: "any",
  })
  async deleteDeclarationArticlesEvaluation(
    @graphql.Args() args: DeleteDeclarationArticlesEvaluationArgs
  ): Promise<DeclarationArticlesEvaluation | null> {
    try {
      return await this.service.deleteDeclarationArticlesEvaluation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
