/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { ValidationService } from "../validation.service";
import { ValidationCreateInput } from "./ValidationCreateInput";
import { ValidationWhereInput } from "./ValidationWhereInput";
import { ValidationWhereUniqueInput } from "./ValidationWhereUniqueInput";
import { ValidationFindManyArgs } from "./ValidationFindManyArgs";
import { ValidationUpdateInput } from "./ValidationUpdateInput";
import { Validation } from "./Validation";

export class ValidationGrpcControllerBase {
  constructor(protected readonly service: ValidationService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Validation })
  @GrpcMethod("ValidationService", "createValidation")
  async createValidation(
    @common.Body() data: ValidationCreateInput
  ): Promise<Validation> {
    return await this.service.createValidation({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Validation] })
  @ApiNestedQuery(ValidationFindManyArgs)
  @GrpcMethod("ValidationService", "validations")
  async validations(@common.Req() request: Request): Promise<Validation[]> {
    const args = plainToClass(ValidationFindManyArgs, request.query);
    return this.service.validations({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Validation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("ValidationService", "validation")
  async validation(
    @common.Param() params: ValidationWhereUniqueInput
  ): Promise<Validation | null> {
    const result = await this.service.validation({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Validation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("ValidationService", "updateValidation")
  async updateValidation(
    @common.Param() params: ValidationWhereUniqueInput,
    @common.Body() data: ValidationUpdateInput
  ): Promise<Validation | null> {
    try {
      return await this.service.updateValidation({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Validation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("ValidationService", "deleteValidation")
  async deleteValidation(
    @common.Param() params: ValidationWhereUniqueInput
  ): Promise<Validation | null> {
    try {
      return await this.service.deleteValidation({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
