/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Validation } from "./Validation";
import { ValidationCountArgs } from "./ValidationCountArgs";
import { ValidationFindManyArgs } from "./ValidationFindManyArgs";
import { ValidationFindUniqueArgs } from "./ValidationFindUniqueArgs";
import { DeleteValidationArgs } from "./DeleteValidationArgs";
import { ValidationService } from "../validation.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Validation)
export class ValidationResolverBase {
  constructor(
    protected readonly service: ValidationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Validation",
    action: "read",
    possession: "any",
  })
  async _validationsMeta(
    @graphql.Args() args: ValidationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Validation])
  @nestAccessControl.UseRoles({
    resource: "Validation",
    action: "read",
    possession: "any",
  })
  async validations(
    @graphql.Args() args: ValidationFindManyArgs
  ): Promise<Validation[]> {
    return this.service.validations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Validation, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Validation",
    action: "read",
    possession: "own",
  })
  async validation(
    @graphql.Args() args: ValidationFindUniqueArgs
  ): Promise<Validation | null> {
    const result = await this.service.validation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Validation)
  @nestAccessControl.UseRoles({
    resource: "Validation",
    action: "delete",
    possession: "any",
  })
  async deleteValidation(
    @graphql.Args() args: DeleteValidationArgs
  ): Promise<Validation | null> {
    try {
      return await this.service.deleteValidation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
