/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DeclarationEvaluationService } from "../declarationEvaluation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeclarationEvaluationCreateInput } from "./DeclarationEvaluationCreateInput";
import { DeclarationEvaluation } from "./DeclarationEvaluation";
import { DeclarationEvaluationFindManyArgs } from "./DeclarationEvaluationFindManyArgs";
import { DeclarationEvaluationWhereUniqueInput } from "./DeclarationEvaluationWhereUniqueInput";
import { DeclarationEvaluationUpdateInput } from "./DeclarationEvaluationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DeclarationEvaluationControllerBase {
  constructor(
    protected readonly service: DeclarationEvaluationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DeclarationEvaluation })
  @nestAccessControl.UseRoles({
    resource: "DeclarationEvaluation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: DeclarationEvaluationCreateInput,
  })
  async createDeclarationEvaluation(
    @common.Body() data: DeclarationEvaluationCreateInput
  ): Promise<DeclarationEvaluation> {
    return await this.service.createDeclarationEvaluation({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DeclarationEvaluation] })
  @ApiNestedQuery(DeclarationEvaluationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DeclarationEvaluation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async declarationEvaluations(
    @common.Req() request: Request
  ): Promise<DeclarationEvaluation[]> {
    const args = plainToClass(DeclarationEvaluationFindManyArgs, request.query);
    return this.service.declarationEvaluations({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DeclarationEvaluation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DeclarationEvaluation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async declarationEvaluation(
    @common.Param() params: DeclarationEvaluationWhereUniqueInput
  ): Promise<DeclarationEvaluation | null> {
    const result = await this.service.declarationEvaluation({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DeclarationEvaluation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DeclarationEvaluation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: DeclarationEvaluationUpdateInput,
  })
  async updateDeclarationEvaluation(
    @common.Param() params: DeclarationEvaluationWhereUniqueInput,
    @common.Body() data: DeclarationEvaluationUpdateInput
  ): Promise<DeclarationEvaluation | null> {
    try {
      return await this.service.updateDeclarationEvaluation({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DeclarationEvaluation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DeclarationEvaluation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDeclarationEvaluation(
    @common.Param() params: DeclarationEvaluationWhereUniqueInput
  ): Promise<DeclarationEvaluation | null> {
    try {
      return await this.service.deleteDeclarationEvaluation({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
