/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { SpecificationService } from "../specification.service";
import { SpecificationCreateInput } from "./SpecificationCreateInput";
import { SpecificationWhereInput } from "./SpecificationWhereInput";
import { SpecificationWhereUniqueInput } from "./SpecificationWhereUniqueInput";
import { SpecificationFindManyArgs } from "./SpecificationFindManyArgs";
import { SpecificationUpdateInput } from "./SpecificationUpdateInput";
import { Specification } from "./Specification";

export class SpecificationGrpcControllerBase {
  constructor(protected readonly service: SpecificationService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Specification })
  @GrpcMethod("SpecificationService", "createSpecification")
  async createSpecification(
    @common.Body() data: SpecificationCreateInput
  ): Promise<Specification> {
    return await this.service.createSpecification({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Specification] })
  @ApiNestedQuery(SpecificationFindManyArgs)
  @GrpcMethod("SpecificationService", "specifications")
  async specifications(
    @common.Req() request: Request
  ): Promise<Specification[]> {
    const args = plainToClass(SpecificationFindManyArgs, request.query);
    return this.service.specifications({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Specification })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("SpecificationService", "specification")
  async specification(
    @common.Param() params: SpecificationWhereUniqueInput
  ): Promise<Specification | null> {
    const result = await this.service.specification({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Specification })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("SpecificationService", "updateSpecification")
  async updateSpecification(
    @common.Param() params: SpecificationWhereUniqueInput,
    @common.Body() data: SpecificationUpdateInput
  ): Promise<Specification | null> {
    try {
      return await this.service.updateSpecification({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Specification })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("SpecificationService", "deleteSpecification")
  async deleteSpecification(
    @common.Param() params: SpecificationWhereUniqueInput
  ): Promise<Specification | null> {
    try {
      return await this.service.deleteSpecification({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
