/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DeclarationTaxService } from "../declarationTax.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeclarationTaxCreateInput } from "./DeclarationTaxCreateInput";
import { DeclarationTax } from "./DeclarationTax";
import { DeclarationTaxFindManyArgs } from "./DeclarationTaxFindManyArgs";
import { DeclarationTaxWhereUniqueInput } from "./DeclarationTaxWhereUniqueInput";
import { DeclarationTaxUpdateInput } from "./DeclarationTaxUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DeclarationTaxControllerBase {
  constructor(
    protected readonly service: DeclarationTaxService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DeclarationTax })
  @nestAccessControl.UseRoles({
    resource: "DeclarationTax",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: DeclarationTaxCreateInput,
  })
  async createDeclarationTax(
    @common.Body() data: DeclarationTaxCreateInput
  ): Promise<DeclarationTax> {
    return await this.service.createDeclarationTax({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DeclarationTax] })
  @ApiNestedQuery(DeclarationTaxFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DeclarationTax",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async declarationTaxes(
    @common.Req() request: Request
  ): Promise<DeclarationTax[]> {
    const args = plainToClass(DeclarationTaxFindManyArgs, request.query);
    return this.service.declarationTaxes({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DeclarationTax })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DeclarationTax",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async declarationTax(
    @common.Param() params: DeclarationTaxWhereUniqueInput
  ): Promise<DeclarationTax | null> {
    const result = await this.service.declarationTax({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DeclarationTax })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DeclarationTax",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: DeclarationTaxUpdateInput,
  })
  async updateDeclarationTax(
    @common.Param() params: DeclarationTaxWhereUniqueInput,
    @common.Body() data: DeclarationTaxUpdateInput
  ): Promise<DeclarationTax | null> {
    try {
      return await this.service.updateDeclarationTax({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DeclarationTax })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DeclarationTax",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDeclarationTax(
    @common.Param() params: DeclarationTaxWhereUniqueInput
  ): Promise<DeclarationTax | null> {
    try {
      return await this.service.deleteDeclarationTax({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
