/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeclarationTax } from "./DeclarationTax";
import { DeclarationTaxCountArgs } from "./DeclarationTaxCountArgs";
import { DeclarationTaxFindManyArgs } from "./DeclarationTaxFindManyArgs";
import { DeclarationTaxFindUniqueArgs } from "./DeclarationTaxFindUniqueArgs";
import { DeleteDeclarationTaxArgs } from "./DeleteDeclarationTaxArgs";
import { DeclarationTaxService } from "../declarationTax.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => DeclarationTax)
export class DeclarationTaxResolverBase {
  constructor(
    protected readonly service: DeclarationTaxService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DeclarationTax",
    action: "read",
    possession: "any",
  })
  async _declarationTaxesMeta(
    @graphql.Args() args: DeclarationTaxCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [DeclarationTax])
  @nestAccessControl.UseRoles({
    resource: "DeclarationTax",
    action: "read",
    possession: "any",
  })
  async declarationTaxes(
    @graphql.Args() args: DeclarationTaxFindManyArgs
  ): Promise<DeclarationTax[]> {
    return this.service.declarationTaxes(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => DeclarationTax, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DeclarationTax",
    action: "read",
    possession: "own",
  })
  async declarationTax(
    @graphql.Args() args: DeclarationTaxFindUniqueArgs
  ): Promise<DeclarationTax | null> {
    const result = await this.service.declarationTax(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DeclarationTax)
  @nestAccessControl.UseRoles({
    resource: "DeclarationTax",
    action: "delete",
    possession: "any",
  })
  async deleteDeclarationTax(
    @graphql.Args() args: DeleteDeclarationTaxArgs
  ): Promise<DeclarationTax | null> {
    try {
      return await this.service.deleteDeclarationTax(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
