version: "3"
services:
  vault:
    image: hashicorp/vault
    restart: on-failure:10
    cap_add:
      - IPC_LOCK
    ports:
      - ${VAULT_PORT}:8200
    command: server
    volumes:
      - vault-data:/vault/file
      - $PWD/config.dev.hcl:/vault/config/config.hcl
  keycloak:
    image: quay.io/keycloak/keycloak
    command: -v start-dev --import-realm
    restart: always
    ports:
      - ${KEYCLOAK_PORT}:8080
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json
    volumes:
      - ./src/keycloak:/opt/keycloak/data/import
  nats:
    image: nats:2.9.15
    networks:
      - internal
    ports:
      - 4222:4222
      - 8222:8222
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - ${JAEGER_AGENT_PORT}:${JAEGER_AGENT_PORT}
      - 14268:14268
      - 14250:4317
  opentelemetry:
    image: otel/opentelemetry-collector:latest
    ports:
      - ${OTEL_COLLECTOR_PORT_GRPC}:${OTEL_COLLECTOR_PORT_GRPC}
      - ${OTEL_COLLECTOR_PORT_HTTP}:${OTEL_COLLECTOR_PORT_HTTP}
      - 1888:1888
      - 13133:13133
      - 55670:55679
    volumes:
      - ./otel-config.yml:/etc/otel-config.yml
    command:
      - --config=/etc/otel-config.yml
    depends_on:
      - jaeger
  db:
    image: postgres:12
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  vault-data: ~
  postgres: ~
networks:
  internal:
    name: internal
    driver: bridge
