/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DetailedDeclarationArticleService } from "../detailedDeclarationArticle.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DetailedDeclarationArticleCreateInput } from "./DetailedDeclarationArticleCreateInput";
import { DetailedDeclarationArticle } from "./DetailedDeclarationArticle";
import { DetailedDeclarationArticleFindManyArgs } from "./DetailedDeclarationArticleFindManyArgs";
import { DetailedDeclarationArticleWhereUniqueInput } from "./DetailedDeclarationArticleWhereUniqueInput";
import { DetailedDeclarationArticleUpdateInput } from "./DetailedDeclarationArticleUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DetailedDeclarationArticleControllerBase {
  constructor(
    protected readonly service: DetailedDeclarationArticleService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DetailedDeclarationArticle })
  @nestAccessControl.UseRoles({
    resource: "DetailedDeclarationArticle",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: DetailedDeclarationArticleCreateInput,
  })
  async createDetailedDeclarationArticle(
    @common.Body() data: DetailedDeclarationArticleCreateInput
  ): Promise<DetailedDeclarationArticle> {
    return await this.service.createDetailedDeclarationArticle({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DetailedDeclarationArticle] })
  @ApiNestedQuery(DetailedDeclarationArticleFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DetailedDeclarationArticle",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async detailedDeclarationArticles(
    @common.Req() request: Request
  ): Promise<DetailedDeclarationArticle[]> {
    const args = plainToClass(
      DetailedDeclarationArticleFindManyArgs,
      request.query
    );
    return this.service.detailedDeclarationArticles({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DetailedDeclarationArticle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DetailedDeclarationArticle",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async detailedDeclarationArticle(
    @common.Param() params: DetailedDeclarationArticleWhereUniqueInput
  ): Promise<DetailedDeclarationArticle | null> {
    const result = await this.service.detailedDeclarationArticle({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DetailedDeclarationArticle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DetailedDeclarationArticle",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: DetailedDeclarationArticleUpdateInput,
  })
  async updateDetailedDeclarationArticle(
    @common.Param() params: DetailedDeclarationArticleWhereUniqueInput,
    @common.Body() data: DetailedDeclarationArticleUpdateInput
  ): Promise<DetailedDeclarationArticle | null> {
    try {
      return await this.service.updateDetailedDeclarationArticle({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DetailedDeclarationArticle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DetailedDeclarationArticle",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDetailedDeclarationArticle(
    @common.Param() params: DetailedDeclarationArticleWhereUniqueInput
  ): Promise<DetailedDeclarationArticle | null> {
    try {
      return await this.service.deleteDetailedDeclarationArticle({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
