/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ArticlePrintLaunch } from "./ArticlePrintLaunch";
import { ArticlePrintLaunchCountArgs } from "./ArticlePrintLaunchCountArgs";
import { ArticlePrintLaunchFindManyArgs } from "./ArticlePrintLaunchFindManyArgs";
import { ArticlePrintLaunchFindUniqueArgs } from "./ArticlePrintLaunchFindUniqueArgs";
import { DeleteArticlePrintLaunchArgs } from "./DeleteArticlePrintLaunchArgs";
import { ArticlePrintLaunchService } from "../articlePrintLaunch.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ArticlePrintLaunch)
export class ArticlePrintLaunchResolverBase {
  constructor(
    protected readonly service: ArticlePrintLaunchService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ArticlePrintLaunch",
    action: "read",
    possession: "any",
  })
  async _articlePrintLaunchesMeta(
    @graphql.Args() args: ArticlePrintLaunchCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ArticlePrintLaunch])
  @nestAccessControl.UseRoles({
    resource: "ArticlePrintLaunch",
    action: "read",
    possession: "any",
  })
  async articlePrintLaunches(
    @graphql.Args() args: ArticlePrintLaunchFindManyArgs
  ): Promise<ArticlePrintLaunch[]> {
    return this.service.articlePrintLaunches(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ArticlePrintLaunch, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ArticlePrintLaunch",
    action: "read",
    possession: "own",
  })
  async articlePrintLaunch(
    @graphql.Args() args: ArticlePrintLaunchFindUniqueArgs
  ): Promise<ArticlePrintLaunch | null> {
    const result = await this.service.articlePrintLaunch(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ArticlePrintLaunch)
  @nestAccessControl.UseRoles({
    resource: "ArticlePrintLaunch",
    action: "delete",
    possession: "any",
  })
  async deleteArticlePrintLaunch(
    @graphql.Args() args: DeleteArticlePrintLaunchArgs
  ): Promise<ArticlePrintLaunch | null> {
    try {
      return await this.service.deleteArticlePrintLaunch(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
