/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ArticlePrintLaunchService } from "../articlePrintLaunch.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ArticlePrintLaunchCreateInput } from "./ArticlePrintLaunchCreateInput";
import { ArticlePrintLaunch } from "./ArticlePrintLaunch";
import { ArticlePrintLaunchFindManyArgs } from "./ArticlePrintLaunchFindManyArgs";
import { ArticlePrintLaunchWhereUniqueInput } from "./ArticlePrintLaunchWhereUniqueInput";
import { ArticlePrintLaunchUpdateInput } from "./ArticlePrintLaunchUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ArticlePrintLaunchControllerBase {
  constructor(
    protected readonly service: ArticlePrintLaunchService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ArticlePrintLaunch })
  @nestAccessControl.UseRoles({
    resource: "ArticlePrintLaunch",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ArticlePrintLaunchCreateInput,
  })
  async createArticlePrintLaunch(
    @common.Body() data: ArticlePrintLaunchCreateInput
  ): Promise<ArticlePrintLaunch> {
    return await this.service.createArticlePrintLaunch({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ArticlePrintLaunch] })
  @ApiNestedQuery(ArticlePrintLaunchFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ArticlePrintLaunch",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async articlePrintLaunches(
    @common.Req() request: Request
  ): Promise<ArticlePrintLaunch[]> {
    const args = plainToClass(ArticlePrintLaunchFindManyArgs, request.query);
    return this.service.articlePrintLaunches({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ArticlePrintLaunch })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ArticlePrintLaunch",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async articlePrintLaunch(
    @common.Param() params: ArticlePrintLaunchWhereUniqueInput
  ): Promise<ArticlePrintLaunch | null> {
    const result = await this.service.articlePrintLaunch({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ArticlePrintLaunch })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ArticlePrintLaunch",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ArticlePrintLaunchUpdateInput,
  })
  async updateArticlePrintLaunch(
    @common.Param() params: ArticlePrintLaunchWhereUniqueInput,
    @common.Body() data: ArticlePrintLaunchUpdateInput
  ): Promise<ArticlePrintLaunch | null> {
    try {
      return await this.service.updateArticlePrintLaunch({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ArticlePrintLaunch })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ArticlePrintLaunch",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteArticlePrintLaunch(
    @common.Param() params: ArticlePrintLaunchWhereUniqueInput
  ): Promise<ArticlePrintLaunch | null> {
    try {
      return await this.service.deleteArticlePrintLaunch({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
